CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)


#########

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


randomtestresults: randomtestadventurer.c randomtestcard1.c randomtestcard2.c dominion.h dominion.c rngs.o

	echo "Result for running random adventurer card test:" > randomtestresults.out
	echo "randomtestadventurer.c: " >> randomtestresults.out
	gcc -o randomtestadventurer dominion.c randomtestadventurer.c  rngs.o $(CFLAGS)
	./randomtestadventurer >> randomtestresults.out
	gcov -f -b dominion.c >> randomtestresults.out
	
	echo "Result for running random village card test:" >> randomtestresults.out
	echo "randomtestcard1.c: " >> randomtestresults.out
	gcc -o randomtestcard1 dominion.c randomtestcard1.c  rngs.o $(CFLAGS)
	./randomtestcard1 >> randomtestresults.out
	gcov -f -b dominion.c >> randomtestresults.out
	
	echo "Result for running random embargo card test:" >> randomtestresults.out
	echo "randomtestcard2.c: " >> randomtestresults.out
	gcc -o randomtestcard2 dominion.c randomtestcard2.c  rngs.o $(CFLAGS)
	./randomtestcard2 >> randomtestresults.out
	gcov -f -b dominion.c >> randomtestresults.out





player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player randomtestresults

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
